import { useState } from 'react'
import { ProductCard } from '../../components/store/ProductCard'
import { StoreIcon } from '../../components/store/StoreHeader'
import { useCart } from '../../context/cartHooks'
import { useProduct, useProducts } from '../../hooks/useProducts'

export function ProductDetailsPage({ productId }: { productId: string }) {
  const { product, loading, error, retry } = useProduct(productId)
  const { products: categoryProducts } = useProducts({ category: product?.categorySlug }, Boolean(product?.categorySlug))
  const [quantity, setQuantity] = useState(1)
  const { addItem } = useCart()
  const [added, setAdded] = useState(false)
  if (loading) return <main className="store-not-found"><div className="store-container"><span className="section-kicker">PRODUCT DETAILS</span><h1>Loading product…</h1></div></main>
  if (error || !product) return <main className="store-not-found"><div className="store-container"><span className="section-kicker">{error ? 'UNABLE TO LOAD PRODUCT' : "SORRY, WE COULDN'T FIND THAT"}</span><h1>{error ? 'Product unavailable' : 'Product not found'}</h1><p>{error || 'This product may have moved or is no longer available in the catalog.'}</p>{error && <button className="store-button store-button-dark" onClick={retry}>Try again</button>} <a href="/shop" className="store-button store-button-dark">Back to shop <StoreIcon name="arrow" size={16} /></a></div></main>
  const related = categoryProducts.filter((item) => item.id !== product.id)
  return <main className="product-details-page"><div className="store-container"><a href="/shop" className="back-to-shop">← Back to shop</a><div className="product-details"><div className={`details-visual product-visual-${product.tone}`}>{product.badge && <span className="product-badge">{product.badge}</span>}{product.imageUrl ? <img className="product-photo" src={product.imageUrl} alt={product.name} /> : <div className={`product-art product-art-${product.visual}`}><span>{product.name.slice(0, 2).toUpperCase()}</span></div>}</div><div className="details-copy"><span className="product-category">{product.category}</span><h1>{product.name}</h1><div className="details-price"><strong>{product.price}</strong>{product.oldPrice && <del>{product.oldPrice}</del>}</div><p className="details-description">{product.description}</p><div className={`stock-status ${product.stockQuantity === 0 ? 'out-of-stock' : ''}`}><span /> {product.stock}</div><div className="quantity-row"><span>Quantity</span><div className="quantity-control"><button onClick={() => setQuantity(Math.max(1, quantity - 1))} aria-label="Decrease quantity">−</button><strong>{quantity}</strong><button onClick={() => setQuantity(quantity + 1)} aria-label="Increase quantity">+</button></div></div><button className="store-button store-button-dark details-add" disabled={product.stockQuantity === 0} onClick={() => { void addItem(product, quantity).then((success) => { if (success) setAdded(true) }) }}>{product.stockQuantity === 0 ? 'Out of stock' : added ? 'Added to cart' : 'Add to cart'} <StoreIcon name="arrow" size={17} /></button></div></div>{related.length > 0 && <section className="related-products"><div className="store-section-heading"><div><span className="section-kicker">YOU MAY ALSO LIKE</span><h2>More from {product.category.toLowerCase()}.</h2></div></div><div className="product-grid">{related.map((item) => <ProductCard key={item.id} product={item} />)}</div></section>}</div></main>
}
